substitutions:
  friendly_name: bathroom
  name: bathroom
  ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ap_fallback_password: "MnANX95MWad1"
  data_pin: D7 # mosi (use TX instead?)
  clock_pin: D5 #sclk
  lat_pin: D4 # xlat

  sin_pin: D7
  sclk_pin: D5
  xlat_pin: D6
  blank_pin: D8
  gsclk_pin: D3

esp8266:
  board: nodemcuv2 #esp01_1m

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

# Enable logging
logger:

# Enable Home Assistant API
api:
#encryption:
#  key: ${encryption_key}

ota:
  - platform: esphome

wifi:
  ssid: ${ssid}
  password: ${wifi_password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} Fallback Hotspot
    password: ${ap_fallback_password}

captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:

external_components:
  - source:
      type: local
      path: components
    components: [ tlc5940 ]

tlc5940:
  sin_pin: ${sin_pin} # D7
  sclk_pin: ${sclk_pin} # D5
  xlat_pin: ${xlat_pin} # D6
  blank_pin: ${blank_pin} # D8
  gsclk_pin: ${gsclk_pin} # D3

output:
  - platform: tlc5940
    id: output_red
    channel: 0
  - platform: tlc5940
    id: output_green
    channel: 1
  - platform: tlc5940
    id: output_blue
    channel: 2
  - platform: tlc5940
    id: output_test
    channel: 15

light:
  - platform: rgb
    name: "Sample RGB light"
    red: output_red
    green: output_green
    blue: output_blue
  - platform: monochromatic
    name: "Light"
    output: output_test